backend:
  name: github
  repo: cesarleyto/dentalisimo
  branch: main

media_folder: "public/assets/images/blog"
public_folder: "/assets/images/blog"

locale: es

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Categoría", name: "category", widget: "select", options: ["Odontología Infantil", "Ortodoncia y Ortopedia", "Diseño de Sonrisa", "Odontología Digital", "Limpieza y Blanqueamiento", "Cirugía e Implantología", "Endodoncia", "Cirugía Estética Facial", "Dentalísimo"] }
      - { label: "Imagen", name: "heroImage", widget: "image", required: false }
      - { label: "Fecha", name: "pubDate", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Cuerpo", name: "body", widget: "markdown" }